app/models.py
# app/models.py

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager


class Employee(UserMixin, db.Model):
    """
    Create an Employee table
    """

    # Ensures table will be named in plural and not in singular
    # as is the name of the model
    __tablename__ = 'employees'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(60), index=True, unique=True)
    username = db.Column(db.String(60), index=True, unique=True)
    first_name = db.Column(db.String(60), index=True)
    last_name = db.Column(db.String(60), index=True)
    password_hash = db.Column(db.String(128))
    department_id = db.Column(db.Integer, db.ForeignKey('departments.id'))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    is_admin = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        """
        Prevent pasword from being accessed
        """
        raise AttributeError('password is not a readable attribute.')

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<Employee: {}>'.format(self.username)


# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
    return Employee.query.get(int(user_id))


class Department(db.Model):
    """
    Create a Department table
    """

    __tablename__ = 'departments'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), unique=True)
    description = db.Column(db.String(200))
    employees = db.relationship('Employee', backref='department',
                                lazy='dynamic')

    def __repr__(self):
        return '<Department: {}>'.format(self.name)


class Role(db.Model):
    """
    Create a Role table
    """

    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), unique=True)
    description = db.Column(db.String(200))
    employees = db.relationship('Employee', backref='role',
                                lazy='dynamic')

    def __repr__(self):
        return '<Role: {}>'.format(self.name)

app/__init__.py
# app/__init__.py

# third-party imports
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

# local imports
from config import app_config

db = SQLAlchemy()
login_manager = LoginManager()


def create_app(config_name='development'):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')

    Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_message = "You must be logged in to access this page."
    login_manager.login_view = "auth.login"
    Migrate(app, db)

    from app import models

    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    return app

app/admin/__init__.py
# app/admin/__init__.py

from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import views

app/home/__init__.py
# app/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py

from flask import render_template
from flask_login import login_required

from services import heading, asynchrous, details_news
from services.model import HeadLine
from . import home


@home.route('/')
def homepage():
    asynchrous.run([heading.prothom_alo, heading.kaler_kantho], sync=len(HeadLine.data) == 0)
    print("thread finished...exiting")
    stories = HeadLine.data.values()  # heading.prothom_alo() + heading.kaler_kantho()
    return render_template('home/index.html', title="Welcome", headings=stories)


@home.route('/details/<title>')
def news_details(title):
    news = details_news.kaler_kantho(title)
    return render_template('home/dashboard.html', news=news)


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

app/templates/base.html
<!-- app/templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }} | Project Dream Team</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top topnav">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('home.homepage') }}">Project Dream Team</a>
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <!-- Modify nav bar menu -->
            <ul class="navbar-nav justify-content-end">
                {% if current_user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
                    <li class="nav-item"><a class="nav-link"><i class="fa fa-user"></i> Hi, {{ current_user.username }}!</a>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('home.homepage') }}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.register') }}">Register</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="wrapper">
    {% block body %}
    {% endblock %}
    <div class="push"></div>
</div>
<footer>
    <div class="container">
        <!-- Modify footer menu -->
        <ul class="list-inline">
            <li class="list-inline-item"><a href="{{ url_for('home.homepage') }}">Home</a></li>
            <li class="list-inline-item footer-menu-divider">⋅</li>
            {% if current_user.is_authenticated %}
                <li class="list-inline-item"><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            {% else %}
                <li class="list-inline-item"><a href="{{ url_for('auth.register') }}">Register</a></li>
                <li class="list-inline-item footer-menu-divider">⋅</li>
                <li class="list-inline-item"><a href="{{ url_for('auth.login') }}">Login</a></li>
            {% endif %}
        </ul>
        <p class="copyright text-muted small">Copyright © 2016. All Rights Reserved</p>
    </div>
</footer>
</body>
</html>

app/templates/home/dashboard.html
<!-- app/templates/home/dashboard.html -->

{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
    <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        {#<h1>The Dashboard</h1>#}
                        <h3>{{ news.title }}</h3>
                        <hr class="intro-divider">
                    </div>
                    <div class="details-news">
                        <div class="row">
                            {% for image in news.images %}
                                <div class="col-md-6">
                                    <div class="thumbnail">
                                        <img src="{{ image }}" alt="No Image" style="width:100%">
                                        <div class="caption">
                                            <p>{{ news.title }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div>{{ news.details|safe }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/home/index.html
<!-- app/templates/home/index.html -->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
    {# <div class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Project Dream Team</h1>
                        <h3>The best company in the world!</h3>
                        <hr class="intro-divider">
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div> #}
    <div class="container">
        {% for heading in headings %}
            <blockquote class="blockquote text-right">
                <p class="mb-0">{{ heading.title }}</p>
                <div class="blockquote-footer">Published in
                    <cite><a target="_blank" href="{{ heading.source_url }}">{{ heading.source }}</a></cite>
                    at {{ heading.published }}. <a href="{{ url_for('home.news_details', title=heading.title) }}">Details</a>
                </div>
            </blockquote>
        {% endfor %}
    </div>
{% endblock %}